# Python Intro 🐍
#### Este ejercicio tiene como objetivo practicar algunas nociones básicas de Python
https://github.com/Daniel1martinez2/sti-23-1-python-intro-exercises/blob/main/python-intro.ipynb

## 📕 Operaciones con Strings (str)



Dividir el string dado según los espacios, obteniendo como resultado una lista de las palabras

In [1]:
s = "The universe doesn't allow perfection"
print(s.split( ))

['The', 'universe', "doesn't", 'allow', 'perfection']


Dado el siguiente texto construya un programa que cuente los caracteres sin contar los espacios:



In [16]:
s = "El pasado puede doler, pero tal como yo lo veo, puedes huir o aprender de él"
number = 0
for word in s.split( ):
    for letter in word:
        number +=1
print(number)


61


Dado el siguiente texto, remplazar la palbra "apple" por "banana"



In [18]:
s = "If you wish to make an apple pie from scratch, you must first invent the universe"
newString = s.replace("an apple", "a banana")
print(newString)

If you wish to make a banana pie from scratch, you must first invent the universe


Usar .format() para imprimir el siguiente string:



In [20]:
s = "The diameter of {planet} is {diameter} kilometers"
planet = "Earth"
diameter = 12742

print(s.format(planet = planet, diameter = diameter))

The diameter of Earth is 12742 kilometers


## 🍕 Operaciones con Listas



Dada la siguiente lista, obtener los primeros 3 elementos en una lista disferente (no modificar la lista original)


In [25]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
newLst = lst[3:]
print(f'lst: {lst}, newLst: {newLst}')


lst: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], newLst: [3, 4, 5, 6, 7, 8, 9, 10]


Dada la siguiente lista, obtener los últimos 3 elementos en una lista diferente (no modificar la lista original)



In [36]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
newLst = list(reversed(lst))
newLst = list(reversed(newLst[:3]))
print(f'lst: {lst}, newLst: {newLst}')

lst: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], newLst: [8, 9, 10]


Dada la siguiente lista, obtener solo los números pares



In [37]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
newLst = []
for num in lst:
    if num % 2 == 0:
        newLst.append(num)
print(newLst)

[0, 2, 4, 6, 8, 10]


Dada la siguiente lista, revertir la lista



In [38]:
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
newLst = list(reversed(lst))
print(newLst)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


Ordenar la siguiente lista de menor a mayor



In [1]:
lst = [4, 1, 6, 12, 3, 2, 1, 7, 1, 0, 14]

lst.sort()
print(lst)

[0, 1, 1, 1, 2, 3, 4, 6, 7, 12, 14]


Dada la siguiente lista, seleccionar e imprimir la palabra "Hello"

In [2]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

word = lst[3][1][2][0]
print(word)


hello


Ordenar la siguiente lista de diccionarios de mayor a menor y de menor a mayor según el valor de 'age'


In [7]:
lst = [
    {
        "name": "A",
        "age": 12
    },
        {
        "name": "B",
        "age": 22
    },
        {
        "name": "C",
        "age": 2
    },
        {
        "name": "D",
        "age": 4
    },
        {
        "name": "E",
        "age": 42
    },
]

lstAsc = sorted(lst, key=lambda x: x['age'])

lstDesc = sorted(lst, key=lambda x: x['age'], reverse=True)

print("Menor a mayor:", lstAsc)
print("Mayor a menor:", lstDesc)

Menor a mayor: [{'name': 'C', 'age': 2}, {'name': 'D', 'age': 4}, {'name': 'A', 'age': 12}, {'name': 'B', 'age': 22}, {'name': 'E', 'age': 42}]
Mayor a menor: [{'name': 'E', 'age': 42}, {'name': 'B', 'age': 22}, {'name': 'A', 'age': 12}, {'name': 'D', 'age': 4}, {'name': 'C', 'age': 2}]


## 🔥 Funciones

Crear una función que reciba de entrada un correo electrónico en formato string, y retorne el dominio (lo que va desúes de @)

Entrada: user@domain.com
Salida esperada: domain.com

In [10]:
def getDominio():
    correo = input("Introduce tu correo electrónico: ")
    dominio = correo.split('@')[1]
    return dominio

dominio = getDominio()
print("Dominio:", dominio)

Dominio: gmail.com


Usar la expresión lambda para filtrar las palabras que no inicien en s de la siguiente lista

In [11]:
seq = ['soup','dog','salad','cat','great']

filtrado = list(filter(lambda palabra: palabra[0] != 's', seq))
print(filtrado)

['dog', 'cat', 'great']


Crear una función que reciba 2 parámetros, el primero un frase, y el segundo una palabra (ambos son de tipo string), esta función recisará si la palabra (segundo parámetro) se enceuntra en la frase (primer parámetro), slo retornará True o False según el caso.

In [13]:
def containsWord(phrase, word):
    return word in phrase

phrase = "Don't tell no lies 'bout me and I won't tell truths 'bout you"
word = "truths"

result = containsWord(phrase, word)
print(result)

True


Cree una función básica que devuelva True si la palabra 'dog' está contenida en el string dado



In [14]:
def containsDog(s):
    return 'dog' in s

s = "Is there a dog here?"
result = containsDog(s)
print(result)

True


Cree una función que cuente el número de veces que aparece la palabra "dog" en el string dado



In [15]:
def countDog(s):
    return s.count('dog')

s = "This dog runs faster than the other dog dude!"
result = countDog(s)
print(result)

2


## 🍎 Numpy básico

Importa numpy como np

In [ ]:
#pip install numpy --no-cache-dir
import numpy as np

Crea un arreglo de 10 ceros



In [17]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crea un arreglo de 10 unos



In [18]:
import numpy as np
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Crea un arreglo de 10 cincos


In [20]:
import numpy as np
arr = np.full(10, 5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


Crea un areglo de enteros (int) de 10 a 50

In [21]:
import numpy as np
arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Crea una matrix de 3x3 con los valores de 0 a 8 -> Revisar método reshape

In [22]:
import numpy as np
values = np.arange(9)
matrix = values.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Crea un arreglo de tamaño 20 lleno de valores aleatorios entre 10 y 100



In [23]:
import numpy as np
arr = np.random.randint(10, 100, size=20)
print(arr)

[54 92 46 65 42 13 66 20 54 63 96 88 46 78 34 13 69 48 68 50]


## 🎋 Pandas básico


Importa pandas como pd

In [24]:
#pip install pandas
import pandas as pd

Leer Salaries.csv como un dataframe y llamarlo sal



In [28]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
print(sal)

            Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148

Revisar el head del dataframe (usar el métdodo head())



In [29]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
print(sal.head())

   Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisc

¿Cual es el BasePay promedio?

In [31]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
meanBasepay = sal['BasePay'].mean()
print("El promedio de BasePay es:", meanBasepay)

El promedio de BasePay es: 66325.4488404877


¿Cuál es la cantidad más alta de OvertimePay en el conjunto de datos?



In [33]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
maxOvertimePay = sal['OvertimePay'].max()
print("La cantidad más alta de OvertimePay es:", maxOvertimePay)


La cantidad más alta de OvertimePay es: 245131.88


¿Cuál es el cargo de JOSEPH DRISCOLL? Nota: use mayúsculas, de lo contrario, puede obtener una respuesta que no coincida (también hay un Joseph Driscoll en minúsculas)

In [35]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
josephDriscoll = sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']
title = josephDriscoll['JobTitle'].values[0]
print("El cargo de Joseph Driscoll es:", title)

El cargo de Joseph Driscoll es: CAPTAIN, FIRE SUPPRESSION


¿Cuál es el nombre de la persona mejor pagada (incluidos los beneficios)?



In [36]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
bestPayed = sal.loc[sal['TotalPayBenefits'].idxmax()]
nameBestPayed = bestPayed['EmployeeName']
print("La persona mejor pagada es:", nameBestPayed)

El nombre de la persona mejor pagada es: NATHANIEL FORD


¿Cuántos títulos de trabajo únicos hay?



In [38]:
import pandas as pd

sal = pd.read_csv('Salaries.csv')
uniqueTitles = sal['JobTitle'].nunique()
print("Número de títulos de trabajo únicos:", uniqueTitles)

Número de títulos de trabajo únicos: 2159
